name: dopavalue
channels:
  - ome
  - ilastik-forge
  - conda-forge
  - anaconda
  - defaults
dependencies:
  # python components
  - python==3.9
#  - marimo
  # OMERO
#  - omero-py
  # Ilastik
  - ilastik==1.4.1.post1
#  - scikit-image==0.22.0
